apiVersion: skaffold/v3
kind: Config
manifests:
  rawYaml:
    - infra/k8s/*
build:
  googleCloudBuild:
    projectId: ticketing-dev-375119
  artifacts:
    - image: us.gcr.io/ticketing-dev-375119/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: us.gcr.io/ticketing-dev-375119/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
